# global context
[build]
  publish = "dist"
  command = "gulp build"

[[redirects]]
  from = "/socials"
  to = "https://jesusrmz.com/socials.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}